[package]
name = "prc"
version = "0.1.0"
edition = "2021"

[lib]
name = "prc"
crate-type = ["cdylib", "lib"]

[dependencies]
aes = "0.8.4"
lazy_static = "1.5.0"
pem = "3.0.5"
pyo3 = "0.23.1"
rand = "0.8.5"
